# Change these first
owner: DHBW-VS # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: DHBW VS Website
    url: https://www.dhbw-vs.de/
  - name: DHBW VS Internal API
    url: $DHBW_VS_INTERNAL_API_URL
    headers:
      - "Authorization: Bearer $DHBW_VS_INTERNAL_API_AUTH_TOKEN"
      - "Content-Type: application/x-www-form-urlencoded"
    expectedStatusCodes:
      - 200
  - name: DHBW VS External API
    url: $DHBW_VS_EXTERNAL_API_URL
    expectedStatusCodes:
      - 404
  - name: DHBW Rapla Website
    url: $DHBW_RAPLA_URL
    __dangerous__body_down_if_text_missing: 'Server running'

assignees:
  - robingenz

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
